name: Build Vivify Quest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup QPM
        uses: iced-mocha/setup-qpm@v1
        with:
          version: 'latest'

      - name: QPM Dependencies
        run: |
          qpm restore
          
      - name: Build Mod
        run: |
          qpm qmod build
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Vivify-Quest-v1.40.8
          path: './build/*.qmod'
